services:
  frps:
    image: fatedier/frps:v0.65.0
    container_name: frps
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml:ro
    command: ["-c", "/etc/frp/frpc.toml"]